# Generated by Django 5.2.4 on 2025-07-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_name', models.CharField(max_length=100)),
                ('Food_cat', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('img', models.URLField(default='https://static.vecteezy.com/system/resources/thumbnails/038/968/845/small_2x/modern-fast-food-restaurant-png.png')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
